### ISSUE TITLE
Will camera stream work?

### ISSUE THREAD

**Issue by fredsco** [nopnop2002/python-esp8266#3]
Given that this setup allows for an usb0 interface to be active with internet connection. 

- Will I be able to stream the camera footage like in the Luckfox examples using rtp. Is the transmission rate enough for 30fps 3M 
- Can I set it to AP? (let a mobile device connect to the Luckfox so it can access the stream)

**Comment by nopnop2002** [comment]
Camera stream is not possible because the UART is slow.

AT firmware provides simple modem functionality.

AT firmware can convert input data from UART into WiFi packets.

**Comment by nopnop2002** [comment]
stream the camera footage using UART is not practical.

Probably not even 1fps.
